services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: rcm
      POSTGRES_PASSWORD: rcm
      POSTGRES_DB: rcm
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rcm"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  temporal:
    image: temporalio/auto-setup:1.23.0
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=rcm
      - POSTGRES_PWD=rcm
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233"
    depends_on:
      - postgres

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8000
    ports:
      - "8088:8080"
    depends_on:
      - temporal

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - APP_ENV=local
      - DATABASE_URL=postgresql+psycopg://rcm:rcm@postgres:5432/rcm
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=rcm-artifacts
      - TEMPORAL_TARGET=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=portal
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; urllib.request.urlopen(\"http://localhost:8000/healthz\"); sys.exit(0)' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
      temporal:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - APP_ENV=local
      - DATABASE_URL=postgresql+psycopg://rcm:rcm@postgres:5432/rcm
      - REDIS_URL=redis://redis:6379/0
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_REGION=us-east-1
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=rcm-artifacts
      - TEMPORAL_TARGET=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=portal
    depends_on:
      api:
        condition: service_healthy
      temporal:
        condition: service_started
