FROM python:3.11-slim
WORKDIR /app
ENV POETRY_VIRTUALENVS_CREATE=false \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN pip install --no-cache-dir poetry==1.8.3
COPY backend /app/backend
COPY pyproject.toml README.md alembic.ini /app/
COPY migrations /app/migrations
RUN poetry install --no-interaction --no-ansi
COPY docker/entrypoint_api.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]
